name: foundation_features
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - cpuonly             # ensure PyTorch CPU-only
  - pytorch=2.0.*       # PyTorch (CPU version via 'cpuonly' meta-package)
  - ffmpeg              # audio decoding dependency for Whisper
  - pip
  - pip:
    - openai-whisper

